### PR TITLE
Move the cluster parameter from sign_and_send_transaction to authorize

### LINKED ISSUE #139: Move cluster parameter from sign_and_send_transaction to authorize
This will align with spec changes made in #111

### PR DESCRIPTION
**Pull request by sdlaver**
Fixes #139

### CODE REVIEW

**Comment by sdlaver** [comment]
@creativedrewy FYI for some minor changes to `clientlib-ktx`
@steveluscher FYI for some more JS changes needed (hopefully trivial!)

**Review by creativedrewy — APPROVED** [review]
I like it! After this is the api baked enough for me to update the ktx lib?

**Comment by sdlaver** [comment]
> I like it! After this is the api baked enough for me to update the ktx lib?

I'd wait until https://github.com/solana-mobile/mobile-wallet-adapter/issues/143 also lands. After that, I expect any subsequent API contract changes to be much more minor.

**Comment by creativedrewy** [comment]
I have no problem waiting 😁

**Comment by steveluscher** [comment]
Starting this now.

**Comment by steveluscher** [comment]
Done.

**Review by steveluscher — APPROVED** [review]

**Pull request merged**
