### PR TITLE
reauthorize now returns the same response object as authorize

### LINKED ISSUE #143: Re-enumerate account addresses on reauthorize
This will align with spec changes made in #111

### PR DESCRIPTION
**Pull request by sdlaver**
Fixes #143
This will support a future change to allow wallets to update account addresses
and wallet URI base on calls to reauthorize, allow for more dynamic usage of
auth tokens.

### CODE REVIEW

**Comment by sdlaver** [comment]
Leaving in draft until we have the corresponding JS changes ready and tested.

**Comment by sdlaver** [comment]
Also, I'm finally tired of the monolithic implementation of AuthRepository.java; I filed https://github.com/solana-mobile/mobile-wallet-adapter/issues/164 to clean it up (using data access objects).

**Comment by steveluscher** [comment]
Added JS changes

**Review by steveluscher — APPROVED** [review]
I didn't see any fakedapp changes in this PR, but wanted to ask: if `reauthorize` sends it a new public key in position zero, does it behave sensibly?

**Comment by sdlaver** [comment]
> I didn't see any fakedapp changes in this PR, but wanted to ask: if `reauthorize` sends it a new public key in position zero, does it behave sensibly?

Good call. I was thinking I needed to wait for #44 to properly handle addresses in `reauthorize`, but I should update the fakedapp public key from `addresses[0]`

**Comment by steveluscher** [comment]
If you want to do the Kotlin/Java merge conflict and then just leave me with conflict markers, I'll do the rest of it, @sdlaver.

**Comment by steveluscher** [comment]
But, also, it's just this:

```
                await this.transact(async (wallet) => {
                    const authorizationResult = await wallet.authorize({
                        cluster: this._cluster,
                        identity: this._appIdentity,
                    });
                    this.handleAuthorizationResult(authorizationResult); // TODO: Evaluate whether there's any threat to not `awaiting` this expression
                });
```

and this:

```
                await this.transact(async (wallet) => {
                    const authorizationResult = await wallet.authorize({
                        cluster: this._cluster,
                        identity: this._appIdentity,
                    });
                    this.handleAuthorizationResult(authorizationResult); // TODO: Evaluate whether there's any threat to not `awaiting` this expression
                });
```

**Pull request merged**
