### PR TITLE
Use strict inequality operator for sequence number check

### PR DESCRIPTION
**Pull request by sdlaver**

### CODE REVIEW

**Review by ankur2136 — APPROVED** [review]

**Comment by steveluscher** [comment]
There was another file in the last PR, yeah?

**Review by steveluscher — CHANGES_REQUESTED** [review]
There was another file in the last PR, yeah?

**Comment by sdlaver** [comment]
> There was another file in the last PR, yeah?

https://github.com/solana-mobile/mobile-wallet-adapter/pull/260
There was a Java file as well. Java's two equality tests are:
- [`Object.equals`](https://docs.oracle.com/javase/7/docs/api/java/lang/Object.html#equals(java.lang.Object))
- `==`

The types being compared are `int` and `int`, hence `==` is the appropriate comparison.

**Review by steveluscher — APPROVED** [review]
Guh. Sorry. Both times I was reading your PRs I was on mobile, where positively every useful bit of context is cut off in the UI in some way.

**Pull request merged**
